// <auto-generated />
namespace Angular.Nag.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Accessories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accessories));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050003132_Accessories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
